alter table public.game_state
add column if not exists "bonusCount" integer not null default 0;

alter table public.game_state
add column if not exists "bonusStack" integer not null default 0;

create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  finished_at timestamptz not null default timezone('utc', now()),
  title text,
  players integer not null default 0,
  rebuys integer not null default 0,
  addon_count integer not null default 0,
  bonus_count integer not null default 0,
  bonus_stack integer not null default 0,
  total_stack integer not null default 0,
  levels_played integer not null default 0
);

alter table public.tournaments
add column if not exists bonus_count integer not null default 0;

alter table public.tournaments
add column if not exists bonus_stack integer not null default 0;

alter table public.tournaments enable row level security;

drop policy if exists "tournaments_select_all" on public.tournaments;
create policy "tournaments_select_all"
on public.tournaments
for select
using (true);

drop policy if exists "tournaments_insert_all" on public.tournaments;
create policy "tournaments_insert_all"
on public.tournaments
for insert
with check (true);
