alter table public.game_state
  add column if not exists "tournamentMode" text not null default 'garage';

alter table public.game_state
  add column if not exists "lateRegistrationClosedAt" bigint;

alter table public.game_state
  add column if not exists "lateRegistrationPlayers" integer;

create table if not exists public.live_tournament_players (
  id text primary key,
  session_id bigint not null,
  tournament_bot_id bigint,
  bot_registration_id text,
  telegram_id bigint,
  name text not null,
  username text,
  source text not null default 'bot',
  registration_source text not null default 'registered',
  status text not null default 'registered',
  arrival_status text not null default 'absent',
  rebuy_count integer not null default 0,
  addon_count integer not null default 0,
  bounty integer not null default 0,
  payment_due integer not null default 0,
  payment_method text not null default 'unpaid',
  place integer,
  place_override boolean not null default false,
  bustout_order integer,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists live_tournament_players_session_idx
  on public.live_tournament_players (session_id, sort_order, created_at);

alter table public.live_tournament_players replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'live_tournament_players'
  ) then
    alter publication supabase_realtime add table public.live_tournament_players;
  end if;
end $$;

alter table public.live_tournament_players enable row level security;

drop policy if exists "live_tournament_players_select_all" on public.live_tournament_players;
create policy "live_tournament_players_select_all"
on public.live_tournament_players
for select
using (true);

drop policy if exists "live_tournament_players_insert_all" on public.live_tournament_players;
create policy "live_tournament_players_insert_all"
on public.live_tournament_players
for insert
with check (true);

drop policy if exists "live_tournament_players_update_all" on public.live_tournament_players;
create policy "live_tournament_players_update_all"
on public.live_tournament_players
for update
using (true)
with check (true);

drop policy if exists "live_tournament_players_delete_all" on public.live_tournament_players;
create policy "live_tournament_players_delete_all"
on public.live_tournament_players
for delete
using (true);

create table if not exists public.tournament_result_exports (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  tournament_bot_id bigint,
  tournament_title text,
  tournament_mode text not null default 'garage',
  payload jsonb not null,
  status text not null default 'failed',
  last_error text,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists tournament_result_exports_session_idx
  on public.tournament_result_exports (session_id, created_at desc);

alter table public.tournament_result_exports enable row level security;

drop policy if exists "tournament_result_exports_select_all" on public.tournament_result_exports;
create policy "tournament_result_exports_select_all"
on public.tournament_result_exports
for select
using (true);

drop policy if exists "tournament_result_exports_insert_all" on public.tournament_result_exports;
create policy "tournament_result_exports_insert_all"
on public.tournament_result_exports
for insert
with check (true);
